language: python

python:
  - "3.6"

install:
  - python setup.py install
  - pip install -r requirements-dev.txt

script:
  - python -c 'import studentvue'
  - cd docs
  - make html
  - touch build/html/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: docs/build/html
  on:
    branch: master
